import Head from 'next/head'
import { useEffect } from "react"
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Link from "next/link";

import { getAllProducts, getAllCategories } from '../utils/API';

// Import Components
import { Button } from "../components/Button"
import { Product } from "../components/Product"
import { useSearchContext } from '../context/SearchContext';

const inter = Inter({ subsets: ['latin'] })

export default function Home({ products, categories }) {
  const { setItemsToSearchFromFn } = useSearchContext();

  useEffect(()=>{
    setItemsToSearchFromFn(products);
}, []);

  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="shortcut icon" href="/fifty_logo.ico" type="image/x-icon" />
        <title>FiftyStore - Home</title>
      </Head>
      <main className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 md:px-8 mt-10">
        <div className="">
          <h3 className="text-lg lg:text-2xl xl:leading-10 font-bold mb-4">
            Shop By Category
          </h3>
          <div className="flex flex-col justify-center items-center space-y-10">
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 md:gap-x-8 w-full">
              <div className="relative flex justify-center items-center h-full w-full">
                <img className="object-center object-cover h-full w-full" src={`${categories[3]}.webp`} alt="girl-image" />
                <Button href={`/products/category/${categories[3]}`} content={`${categories[3]}`} additional_style={'z-10 absolute'} />
              </div>
              <div className="flex flex-col space-y-4 md:space-y-8 my-4 md:my-0">
                <div className="relative flex justify-center items-center h-full w-full">
                  <img className="object-center object-cover h-full w-full" src={`${categories[0]}.webp`} alt="electronics-image" />
                  <Button href={`/products/category/${categories[0]}`} content={`${categories[0]}`} additional_style={'z-10 absolute'} />
                </div>
                <div className="relative flex justify-center items-center h-full w-full">
                  <img className="object-center object-cover h-full w-full" src={`${categories[1]}.webp`} alt="jewelry-image" />
                  <Button href={`/products/category/${categories[1]}`} content={`${categories[1]}`} additional_style={'z-10 absolute'} />
                </div>
              </div>
              <div className="relative justify-center items-center h-full w-full flex md:hidden lg:flex">
                <img className="object-center object-cover h-full w-full" src={`${categories[2]}.webp`} alt="man-image" />
                <Button href={`/products/category/${categories[2]}`} content={`${categories[2]}`} additional_style={'z-10 absolute'} />
              </div>
            </div>
          </div>
        </div>
        <div className="pb-0.5 my-10">
          <div className="relative px-10 py-8" style={{
            backgroundRepeat: "no-repeat", backgroundImage: "url(https://preview.colorlib.com/theme/divisima/img/banner-bg.jpg.webp)", backgroundSize: "cover",
            backgroundPosition: "top center"
          }}>
            <div className="absolute right-20 bottom-30 font-bold bg-stone-400 uppercase py-2 px-5 rounded-full">New</div>
            <span className="uppercase mb-4 text-lg block tracking-wider font-semibold">New Arrivals</span>
            <h2 className="uppercase font-bold mb-5 text-stone-700 text-3xl xl:text-6xl">WOMENS CLOTHES</h2>
            <Button href={'/products'} content={'shop now'} />
          </div>
        </div>
        <div className="pb-0.5 my-3 mx-auto max-w-7xl sm:px-6 lg:px-8">         
            <h3 className="text-lg lg:text-2xl xl:leading-10 font-bold mb-4">
                Most Recent Products
            </h3>
          <div className="mx-auto grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {products.map((product => <Product 
                        key={product.id} 
                        id={product.id}
                        title={product.title} 
                        description={product.description} 
                        image={product.image}
                        price={product.price}
                        rate={product.rating.rate} />))}
          </div>
          <Button href={'/products'} content={'view more'} additional_style={'block mt-5 mx-auto'} />
        </div>
      </main>
    </>
  )
}

export const getStaticProps = async () => {
  const products = await getAllProducts('products?limit=6');
  const categories = await getAllCategories();
  return {
    props: {
      products,
      categories,
    },
  };
};
